"""add block reminder fields

Revision ID: 11b5f174d692
Revises: ab4d1b5c2bd7
Create Date: 2025-12-21 11:33:10.015365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b5f174d692'
down_revision: Union[str, Sequence[str], None] = 'ab4d1b5c2bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('last_message_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('blocks', sa.Column('reminder_sent', sa.SmallInteger(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'reminder_sent')
    op.drop_column('blocks', 'last_message_at')
    # ### end Alembic commands ###
