"""set defaults for users.is_active and blocks status/type

Revision ID: 9023c5338bca
Revises: 10308d0fa5bb
Create Date: 2025-12-21 00:00:12.741267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9023c5338bca'
down_revision: Union[str, Sequence[str], None] = '10308d0fa5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
