"""add approval_flags to forms

Revision ID: auto
Revises: b6c7c6e1a2f1
Create Date: 2025-12-21 14:42:58.457510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'auto'
down_revision: Union[str, Sequence[str], None] = 'b6c7c6e1a2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('approval_flags', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'approval_flags')
    # ### end Alembic commands ###
