"""Align models to final spec: defaults, constraints, indexes

Revision ID: 10308d0fa5bb
Revises: 12590c59a578
Create Date: 2025-12-20 20:49:40.432449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10308d0fa5bb'
down_revision: Union[str, Sequence[str], None] = '12590c59a578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_blocks_form_id', 'blocks', ['form_id'], unique=False)
    op.create_index('ix_files_message_id', 'files', ['message_id'], unique=False)
    op.create_index('ix_forms_developer_id', 'forms', ['developer_id'], unique=False)
    op.create_index('ix_forms_user_id', 'forms', ['user_id'], unique=False)
    op.create_unique_constraint('uq_forms_subform_id', 'forms', ['subform_id'])
    op.alter_column('functions', 'is_changed',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index('ix_functions_form_id', 'functions', ['form_id'], unique=False)
    op.create_index('ix_licenses_user_id', 'licenses', ['user_id'], unique=False)
    op.create_index('ix_messages_block_id', 'messages', ['block_id'], unique=False)
    op.create_index('ix_messages_user_id', 'messages', ['user_id'], unique=False)
    op.alter_column('nonfunctions', 'is_changed',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index('ix_nonfunctions_form_id', 'nonfunctions', ['form_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.alter_column('users', 'is_active',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_index('ix_nonfunctions_form_id', table_name='nonfunctions')
    op.alter_column('nonfunctions', 'is_changed',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_index('ix_messages_user_id', table_name='messages')
    op.drop_index('ix_messages_block_id', table_name='messages')
    op.drop_index('ix_licenses_user_id', table_name='licenses')
    op.drop_index('ix_functions_form_id', table_name='functions')
    op.alter_column('functions', 'is_changed',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_constraint('uq_forms_subform_id', 'forms', type_='unique')
    op.drop_index('ix_forms_user_id', table_name='forms')
    op.drop_index('ix_forms_developer_id', table_name='forms')
    op.drop_index('ix_files_message_id', table_name='files')
    op.drop_index('ix_blocks_form_id', table_name='blocks')
    # ### end Alembic commands ###
