"""add approval_flags to forms

Revision ID: 20251221_add_approval_flags
Revises: 12590c59a578
Create Date: 2025-12-21 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251221_add_approval_flags'
down_revision = '10308d0fa5bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('approval_flags', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'approval_flags')
    # ### end Alembic commands ###
