"""add blocks reminder scan index

Revision ID: edbe879cab13
Revises: c94f7b4dbc99
Create Date: 2025-12-21 13:47:56.826431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbe879cab13'
down_revision: Union[str, Sequence[str], None] = 'c94f7b4dbc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_blocks_reminder_scan', 'blocks', ['status', 'reminder_sent', 'last_message_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blocks_reminder_scan', table_name='blocks')
    # ### end Alembic commands ###
